name: HipChat
slug: hipchat
access: public

description: "This app can notify you of new tickets, customer replies, agent replies and comments on HipChat."

category: notification

tags:
- hipchat
- chat
- notification

video: https://vimeo.com/77780317

developer: 
  name: Prateek
  email: prateek@supportbee.com
  twitter: "@prateekdayal"
  github: prateekdayal
