name: Batchbook
slug: batchbook
access: public

category: crm

tags: 
- crm
- batchbook

developer: 
  name: Nisanth Chunduru
  email: nisanth074@gmail.com
  twitter: "@nisanth074"
  github: nisanth074
