name: Bulk SMS
slug: bulktext
access: public

description: "Get SMS notifications for new tickets and customer replies via BulkSMS' gateway. You will need a bulksms account that you can signup for by visiting http://www.bulksms.com/"

category: notification

tags: 
- sms
- bulksms

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "prateekdayal"
  github: prateekdayal

retired: true
