name: Teamwork Projects
slug: teamwork
access: public

description: "

Teamwork Projects is an online project management software that helps teams work together more productively online. It is designed to help users manage their day to day projects either in a company or personal setting.

## Send a Ticket to Teamwork Projects as a Task List or a Task in an Existing List

If you often create tasks based on emails that your customers or clients send you, you can use this integration to accomplish task creation in one click. You can choose to create a new task list in Teamwork Projects or add a new task in an existing task list. This can be optionally assigned to a person in the project. We fill in the description of the task list/task with the contents of the email and also add a link to the SupportBee ticket, so your team can follow-up once the task is taken care of. A link to the Teamwork Projects item is also posted on the ticket as a comment.

## Support for Multiple Projects

Our integration lets you pick a project and a task list before sending a ticket over to Teamwork Projects.

## Adding the Teamwork Projects App

To add this integration, click on the 'Add to My SupportBee' button. There is only one field to fill and you are ready to use the integration!

### API Token

Your API token can be found by logging into your Teamwork Projects account, clicking your avatar in the top right, and choosing ‘Edit my details’. On the API tab of the dialog click the 'Show your token' at the bottom (under 'API Authentication tokens').

## Using the App

To send a ticket to Teamwork Projects, open a ticket and click Apps > Send to Teamwork Projects. Before you send the ticket, you can edit the title/description. You can also select a project and an optional task list before sending the ticket over to Teamwork Projects. In case you select an optional task list, you can create a new task for that list and assign that to a person in the project. Once the ticket has been sent to Teamwork Projects, a comment with the URL of the task will be posted on the ticket automatically.

"

category: project-management

tags: 
- project management

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "@prateekdayal"
  github: prateekdayal

# The following config keys are used by Action Handlers
# Set button 'overlay' to true, if you want to have an overlay
# The valid values for screens are [ticket, all, unassigned, my, groups]
# Remove the following section if you do not want to define Action Handlers
 
action:
  button:
    overlay: true
    screens: 
    - ticket
    label: Send To Teamwork Projects
