name: Campfire
slug: campfire
access: public

description: "

Use this app to post new tickets, replies and comments to Campfire!

"

category: notification 

tags:
- campfire
- chat

video: https://vimeo.com/77577714 

developer: 
  name: Avinasha
  email: me@avinasha.com
  twitter: "@avishastry"
  github: avinasha
