name: Basecamp Classic
slug: basecamp_classic
access: public

description: "Send ticket details to an Basecamp Classic project. The ticket is saved as a message on Basecamp"

category: project-management

tags:
- project management

developer:
developer:
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: bopanna

action:
  button:
    overlay: true
    screens:
    - ticket
    - unassigned
    - my_tickets
    - my_team_tickets
    - all
    - labels
    - search
    label: Send To Basecamp Classic
