name: Pivotal Tracker
slug: pivotaltracker
access: public

description: "

Pivotal Tracker is an award winning agile project management tool which not only helps in collaboration but also to get continuous feedback from the customers. For more information visit http://www.pivotaltracker.com/

## Easily send Customer emails from SupportBee to Pivotal Tracker

The Pivotal Tracker app can send your Tickets as Stories to Pivotal. If you get a support ticket that needs some work done, you can create a tracker story and send it to your Icebox without leaving SupportBee.

## Adding the Pivotal Tracker App

To add the app, click on the 'Add to My SupportBee'. If this is the first app that you are adding, you will have to enter your subdomain and you will be taken to a settings screen. Fill in the following details

### Token

Find the token under Profile (in the user menu) > API Token. You would have to click 'Create New Token'

### Access SupportBee on behalf of

Choose the name of the agent/admin from the drop down menu

## Using the App

To use the app, open a ticket and click Apps > Send to Pivotal.
You can edit the Title and Description of the story, and select the Project to which you want the Story to be sent. You can also assign the ticket to an owner, and give it a type. We also put a link to the ticket in the story description.
"

category: project-management 

tags:
- pivotal
- project management

developer: 
  name: Pranav Singh
  email: pranav@supportbee.com
  twitter: "@pranav7"
  github: pranav7

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Pivotal
