name: Pivotal Tracker
slug: pivotaltracker
access: public

description: "

Pivotal Tracker is an award winning agile project management tool which not only helps in collaboration but also to get continuous feedback from the customers. For more information visit http://www.pivotaltracker.com/

## Send customer feedback from SupportBee to Pivotal Tracker in One Click

SupportBee's Pivotal Tracker app can send selected customer tickets to Pivotal. If you get a support ticket that needs some development work done, you can create a tracker story and send it to your backlog without leaving SupportBee.

## Adding the Pivotal Tracker App

To add the app, click on the 'Add to My SupportBee'. If this is the first app that you are adding, you will have to enter your subdomain and you will be taken to a settings screen. Fill in the following details

### Token

Find the token under Profile (in the user menu) > API Token. You would have to click 'Create New Token'

### Project ID

Find Project ID under Access which you can reach via Project > Edit Settings

### Access SupportBee on behalf of

Choose the name of the agent/admin from the drop down menu

## Using the App

To use the app, open a ticket and click Apps > Send to Pivotal. Before you send the ticket to PIvotal you can customize the title or description. We also put a link to the ticket in the story description.

"

category: project-management 

video: 'https://vimeo.com/76779522'


tags:
- pivotal
- project management

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "@prateekdayal"
  github: prateekdayal

action:
  button:
    overlay: true
    screens:
    - ticket
    label: Send To Pivotal
