name: Audit Trail
slug: audit_trail
access: test

description: "An audit trail is a fancy term for having a log that you can look at to know who did what. For example, if you want to find out who trashed a ticket or marked it as spam you would look at the audit trail. Add this app to record information about Archive, Unarchive, Spam, Unspam, Trash and Untrash events. 

We show you when something happened (time) and who did it (name/email address of the agent). Once you add the app, this information is added to the ticket as comments. Everything is recorded automatically with no manual intervention."

category: workflow

tags: 
- workflow
- audit_trail

developer: 
  name: Prateek Dayal
  email: prateek@supportbee.com
  twitter: "prateekdayal"
  github: prateekdayal

retired: true
redirect_visitors_to: "https://supportbee.com/blog/audit-trail-app-becomes-core-feature/"
