name: "Capsule CRM"
slug: "capsule_crm_v2"
access: public

description: "

Capsule is the easy online CRM for doing business. Using a CRM like Capsule you can keep track of people and companies you do business with. You can signup for a trial account by visiting [Capsule's homepage](http://capsulecrm.com/).

## Sync Customer Information between Capsule & SupportBee

Use SupportBee's Capsule app to share information about a customer between CapsuleCRM and SupportBee - automatically on every new ticket! By installing the app you can


*  Fetch a customer's information from Capsule and show it as a comment on the ticket. The comment also contains a link to the customer's profile in Capsule.

*  Update the customer information in Capsule whenever the customer sends a new ticket. Keep your sales team in the loop.


## Adding the Capsule CRM App

To add the app, click on the 'Add to My SupportBee'. If this is the first app that you are adding, you will have to enter your subdomain and you will be taken to a settings screen. Fill in the following details

### Capsule Auth Token

To get an auth token, login to your Capsule account, go to My Preferences (in the User Menu) > API Authentication Token

### Create a New Person in Capsule if one does not exist

Check this option if you want us to create a new contact in Capsule if we can't find one based on the email address of the customer.

### Subdomain

This is your capsule subdomain. If you login to capsule at mycompany.capsulecrm.com, enter mycompany

### Send ticket content to Capsule

By default we only add a link to the SupportBee ticket. If you want the full content of the ticket to be posted to Capsule, please check this option.


## Using the App

Once you add the app, sit back and relax. You don't have to do anything manually. Every time a ticket comes in, we will automatically look in Capsule and post a comment on the ticket if we find a contact based on the email address. If we can't find one, we will create a contact if you have the option checked in settings.

"

category: crm

video : 'https://vimeo.com/77032113'

tags:
- crm
- capsule

developer:
  name: Bopanna D.C
  email: bops.91@gmail.com
  twitter: "@gagan_bopanna"
  github: gagan-bopanna
