name: Compose
slug: compose
access: test

description: "
This app is now deprecated. You can send an email to a customer for new tickets without an app. Please see our [blog post announcing this feature](https://blog.supportbee.com/2013/08/28/send-emails-new-tickets/).

## Send Emails to Customers without creating Tickets
Send a new email from within SupportBee. This app uses your SMTP server to relay the emails
"

category: email 

tags: 
- compose

developer: 
  name: Avinasha S
  email: me@avinasha.com
  twitter: "@avishastry"
  github: avinasha

action:
  button:
    overlay: true
    screens: 
    - ticket
    label: Compose
