name: Mailchimp
slug: mailchimp
access: public

description: "MailChimp Integration with SupportBee.
User Story:
Lets say a user requests for a feature and it would be available in the next upcoming release. For this you will have to track and record the users who requested this(or similar) feature. You can create a campaign in MailChimp and select the list of users whom you'd like to announce regarding the release(feature made available).

For achieving this purpose, you can push a user to a list in mailchimp right from SupportBee.
"

category: Integration

tags: 
- mailchimp
- announcement

developer: 
  name: Swaroop SM
  email: swaroop.striker@gmail.com
  twitter: "@smswaroop"
  github: swaroopsm

action:
  button:
    overlay: true
    screens: 
    - ticket
    label: Send To MailChimp
