name: Flowdock
slug: flowdock
access: public

description: "Send new ticket, reply and comment notifications to Flowdock"

category: notification

tags: 
- flowdock
- chat

video: https://vimeo.com/77796980


developer: 
  name: Prateek
  email: prateek@supportbee.com
  twitter: "@prateekdayal"
  github: prateekdayal
