name: Bugify
slug: bugify
access: public

description: "
[Bugify](https://bugify.com) is a simple PHP issue tracker, designed to offer powerful bug tracking capabilities in an easy to use system.

## Create Bugify Issues from within SupportBee

Using this app, you can send any ticket in SupportBee to Bugify and create an issue. The issue title and description are picked up from the ticket but can be edited. Description also carries a link to the ticket in SupportBee.

## Using the App

To add the app, click on the 'Add to My SupportBee'. On the settings screen, enter the following details

### URL

Your bugify URL (example: http://bugify.com). This is where you go and login to your Bugify.

### API Key

Your Bugify API Key

## Using the App

To use the app, open a ticket and click on Apps > Send to Bugify. You can edit the subject or the description of the issue before you send it to Bugify.

"

category: project-management

tags: 
- bugify
- issue tracking

developer: 
  name: Graham Bradley
  email: hello@gbradley.com
  twitter: "@gmbradley"
  github: gbradley

action:
  button:
    overlay: true
    screens: 
    - ticket
    label: Send to Bugify

retired: true
