name: Mark As Answered Button
slug: mark_answered
access: test

description: "Replying to a ticket changes it from Unanswered to Answered. However sometimes you create a ticket or get a ticket and reply to the customer via phone. If you don't want to archive this ticket yet (you are still working on it) but don't want to keep it around as Unanswered, use this app. It adds a 'Mark As Answered' button in the apps. You can access it from the tickets listing or when you open a single ticket.

You can also leave a comment (optional) explaining why the ticket has been marked as Answered"

category: workflow

tags: 
- workflow
- answered

developer: 
  name: <Your Name>
  email: <Your Email>
  twitter: "<Your Twitter Handle>"
  github: <Your Github Handle>

# The following config keys are used by Action Handlers
# Set button 'overlay' to true, if you want to have an overlay
# The valid values for screens are [ticket, all, unassigned, my, groups]
# Remove the following section if you do not want to define Action Handlers
 
action:
  button:
    overlay: true
    screens: 
    - ticket
    - all
    - unassigned
    label: Mark Answered
    multiple_ticket_selection: true # Let agents select multiple tickets in ticket listings when using the Mark as Answered integration
