name: Magento
slug: magento
access: public

description: "Pulls in order information of the support ticket requester automatically and posts it as a comment on the SupportBee ticket. Also, it adds a note to the corresponding order in Magento. The note has a link to the support ticket on SupportBee."

category: Ecommerce

tags: 
- ecommerce
- magento

retired: true
temporary_redirect_url: "https://supportbee.com/integrations"
developer: 
  name: Bopanna D.C
  email: bops.91@gmail.com
  github: bopanna

